"""add exam_time to exam_session

Revision ID: 87bfbbcb73f5
Revises: d053995ef4ef
Create Date: 2026-08-23 14:19:25.718904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87bfbbcb73f5'
down_revision: Union[str, Sequence[str], None] = 'd053995ef4ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_session', sa.Column('exam_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_session', 'exam_time')
    # ### end Alembic commands ###
