"""initial schema

Revision ID: d053995ef4ef
Revises: 
Create Date: 2026-08-22 14:47:16.122740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd053995ef4ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_session',
    sa.Column('exam_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_name', sa.String(), nullable=False),
    sa.Column('exam_date', sa.String(), nullable=True),
    sa.Column('session_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('exam_id')
    )
    op.create_table('hall',
    sa.Column('hall_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hall_name', sa.String(), nullable=False),
    sa.Column('block', sa.String(), nullable=True),
    sa.Column('rows_count', sa.Integer(), nullable=False),
    sa.Column('cols_count', sa.Integer(), nullable=False),
    sa.Column('seats_per_bench', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('hall_id')
    )
    op.create_table('paper',
    sa.Column('paper_id', sa.String(), nullable=False),
    sa.Column('paper_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('paper_id')
    )
    op.create_table('bench',
    sa.Column('bench_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hall_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('column_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hall_id'], ['hall.hall_id'], ),
    sa.PrimaryKeyConstraint('bench_id')
    )
    op.create_table('course_code_mapping',
    sa.Column('course_code', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('paper_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.paper_id'], ),
    sa.PrimaryKeyConstraint('course_code')
    )
    op.create_table('seat',
    sa.Column('seat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bench_id', sa.Integer(), nullable=False),
    sa.Column('seat_label', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bench_id'], ['bench.bench_id'], ),
    sa.PrimaryKeyConstraint('seat_id')
    )
    op.create_table('student',
    sa.Column('student_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('register_no', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('class', sa.String(), nullable=True),
    sa.Column('course_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_code'], ['course_code_mapping.course_code'], ),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('register_no')
    )
    op.create_table('exam_registration',
    sa.Column('registration_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam_session.exam_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('registration_id'),
    sa.UniqueConstraint('exam_id', 'student_id', name='uq_exam_student')
    )
    op.create_table('allocation',
    sa.Column('allocation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam_session.exam_id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['exam_registration.registration_id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seat.seat_id'], ),
    sa.PrimaryKeyConstraint('allocation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allocation')
    op.drop_table('exam_registration')
    op.drop_table('student')
    op.drop_table('seat')
    op.drop_table('course_code_mapping')
    op.drop_table('bench')
    op.drop_table('paper')
    op.drop_table('hall')
    op.drop_table('exam_session')
    # ### end Alembic commands ###
